import './globals.css'

export const metadata = {
  title: 'My Toy Project',
  description: 'Generated by SHLEE',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>{children}</body>
    </html>
  )
}
